apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: clean-air-agents
spec:
  template:
    spec:
      containers:
        - image: gcr.io/agentic_environmental_management/clean-air-agents:latest
          ports:
            - containerPort: 8000
          env:
            - name: OPENAQ_API_KEY
              value: "6ec68d8941f622785182d711d9e86c98fd839be17aff2cc397ade6c49848b23c"
      containerConcurrency: 1

